### ISSUE TITLE
Close datetimes result in repeated monthly X axis labels

### ISSUE THREAD

**Issue by rcarmo** [Kanaries/pygwalker#28] opened 2023-02-22 14:51 UTC
I'm quite enjoying this, but I have come across a serious data interpretation problem. 

I have a dataframe read like so:

```
df = pd.read_sql_query(query,conn, parse_dates=['date'])
```

However, the datetime values are all relatively high resolution ones (i.e., 5-15 second samples over many days), and the X axis nearly always shows only "2023-02" instead of showing the date (or the hour if I'm looking at the last 24 hours).

Can we get a way to change the X-axis label resolution, or (even better), a stepwise automatic scale to format those datetimes according to the dataset granularity?

**Comment by rcarmo** [comment] 2023-02-23 08:02
Actually, that doesn't work for me because I'm trying to see minute or second-level data for the last hour and the labels still show me YYYY-MM. I would have expected it to have switched to HH:MM at least...

**Comment by ObservedObserver** [comment] 2023-02-23 15:04
I found it is caused by a fixed format string in `graphic-walker`. already fixed in the latest version `@kanaries/graphic-walker/0.2.12`.

After pygwalker upgrades to the latest version of gw, this problem can be fixed. @Asm-Def 

But it has not supported custom label format yet (TODO).

**Comment by Asm-Def** [comment] 2023-02-23 19:19
Fixed and released in version `0.1.4.2`

See pr https://github.com/Kanaries/pygwalker/pull/34.

**Comment by rcarmo** [comment] 2023-02-24 16:13
Wow, thanks! Will reinstall on my instance and get back to you

**Closed** 2023-03-07 13:27 UTC
Labels: bug, good first issue, fixed but needs feedback
