### ISSUE TITLE
HTML not rendered on Databricks runtime 9.1

### ISSUE THREAD

**Issue by ig-perez** [Kanaries/pygwalker#55] opened 2023-02-28 18:59 UTC
Hello, thanks for creating and maintaining this package. Sadly when I try to render the HTML I just got `<IPython.core.display.HTML object>` as output. 

I have tried with:
- `! pip install git+https://github.com/Kanaries/pygwalker@main`
- `!pip install 'pygwalker>=0.1.4a0'`
- `!pip install pygwalker`

All cases showed same result. Any suggestion?

Thanks

**Comment by Asm-Def** [comment] 2023-03-01 04:05
Have you tried this?

https://github.com/Kanaries/pygwalker/issues/10#issuecomment-1447823367

It seems like a problem caused by the security policies of databricks.

**Comment by ig-perez** [comment] 2023-03-01 15:15
I didn't see that popup. By chance do you have the spark or databrick setting I need to modify? There are some settings that can be changed at notebook level, perhaps that's we need here.

**Comment by Asm-Def** [comment] 2023-03-01 17:27
There're several cases that may lead to this result.

https://docs.databricks.com/visualizations/html-d3-and-svg.html

https://stackoverflow.com/questions/67153253/display-ipython-core-display-html-object-in-spark

You can try with a smaller dataframe sample and use `displayHTML(pyg.to_html(df, ...))` instead of `pyg.walk(df, ...)`.

If the problem persists, it would be helpful to share the notebook or a minimum unit of reproduction.

**Comment by longxiaofei** [comment] 2023-07-06 15:10
No feedback for too long, so temporarily closing this issue. If there are any problems, it can be reopened.

**Closed by longxiaofei** 2023-07-06 15:10 UTC
